
package com.stech.test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Test", targetNamespace = "http://test.stech.com/", wsdlLocation = "file:/C:/Users/Santhosh%20C/Desktop/test/Test8897362329597799042.wsdl")
public class Test_Service
    extends Service
{

    private final static URL TEST_WSDL_LOCATION;
    private final static WebServiceException TEST_EXCEPTION;
    private final static QName TEST_QNAME = new QName("http://test.stech.com/", "Test");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Santhosh%20C/Desktop/test/Test8897362329597799042.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TEST_WSDL_LOCATION = url;
        TEST_EXCEPTION = e;
    }

    public Test_Service() {
        super(__getWsdlLocation(), TEST_QNAME);
    }

    public Test_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TEST_QNAME, features);
    }

    public Test_Service(URL wsdlLocation) {
        super(wsdlLocation, TEST_QNAME);
    }

    public Test_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TEST_QNAME, features);
    }

    public Test_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Test_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Test
     */
    @WebEndpoint(name = "TestPort")
    public Test getTestPort() {
        return super.getPort(new QName("http://test.stech.com/", "TestPort"), Test.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Test
     */
    @WebEndpoint(name = "TestPort")
    public Test getTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://test.stech.com/", "TestPort"), Test.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TEST_EXCEPTION!= null) {
            throw TEST_EXCEPTION;
        }
        return TEST_WSDL_LOCATION;
    }

}
